flowchart TD
    Kino[Firma
    Kino] --> Dyrektor[Stanowisko
    Dyrektor kina]

    Dyrektor --> Obsluga[Komórka organizacyjna
    Obsługa klienta]
    Dyrektor --> Technicy[Komórka organizacyjna
    Pracownicy techniczni]
    Dyrektor --> Sprzatacze[Komórka organizacyjna
    Pracownicy sprzątający]
    Dyrektor --> Ochrona[Komórka organizacyjna
    Ochrona]

    Obsluga --> Kasejrzy[Stanowisko
    Kasjerzy]
    Obsluga --> Kontrolerzy[Stanowisko
    Kontrolerzy biletów]

    Technicy --> Planista[Stanowisko
    Planista]
    Technicy --> Technik[Stanowisko
    Technik filmowy]